spring:
  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      printer:
        enabled: true
      introspection:
        enabled: true

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/blog?schema=blog_schema
    name: blog
    username: root
    password: password
    pool:
      max-size: 10
      enabled: true
      initial-size: 2
      max-idle-time: 30m
      validation-query: SELECT 1
  data:
    r2dbc:
      repositories:
        enabled: true

logging:
  level:
    root: info

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - prometheus
        - health
